# Generated by Django 5.0 on 2024-06-11 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('original_name', models.CharField(max_length=256, null=True)),
                ('size', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_s3_url', models.BooleanField(default=False)),
                ('is_350_thumb', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'em_user_file',
            },
        ),
    ]
