# Generated by Django 5.0 on 2024-06-12 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=256, unique=True)),
                ('short_description', models.CharField(max_length=256, null=True)),
                ('product_image', models.CharField(max_length=256, null=True)),
                ('mrp', models.CharField(max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'em_product',
            },
        ),
    ]
