# Generated by Django 5.0 on 2024-06-11 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('mobile', models.CharField(max_length=256, unique=True)),
                ('user_code', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('password', models.CharField(max_length=1000, null=True)),
                ('permissions', models.CharField(max_length=2000, null=True)),
                ('user_type', models.CharField(max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.UUIDField(null=True)),
                ('related_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'em_users',
            },
        ),
        migrations.CreateModel(
            name='UserMagicCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField(null=True)),
                ('device_id', models.CharField(max_length=256, null=True)),
                ('device_type', models.CharField(max_length=256, null=True)),
                ('magic_code', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'em_user_magic_code',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField(null=True)),
                ('user_ip', models.CharField(max_length=256, null=True)),
                ('fcm_token', models.CharField(max_length=256, null=True)),
                ('user_agent', models.CharField(max_length=500, null=True)),
                ('device_id', models.CharField(max_length=256, null=True)),
                ('device_type', models.CharField(max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'em_user_tokens',
            },
        ),
    ]
