# Generated by Django 5.0 on 2024-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_customer_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rm_id',
            field=models.UUIDField(null=True),
        ),
    ]
