# Generated by Django 5.0 on 2024-05-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_unicomorderitems_unicomorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicomorderitems',
            name='reversePickable',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='unicomorderitems',
            name='shelfCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
