# Generated by Django 5.0 on 2024-05-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_unicomorderitems_reversepickable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicomorderitems',
            name='shippingChargeTaxPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
