# Generated by Django 5.0 on 2024-05-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_unicomorderitems_shippingchargetaxpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicomorderitems',
            name='uniCode',
            field=models.CharField(max_length=256),
        ),
    ]
