# Generated by Django 5.0 on 2024-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_unicomorderitems_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uniCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='unicomorders',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
