# Generated by Django 5.0 on 2024-05-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_unicomorders_unicode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnicomOrderItems',
        ),
        migrations.DeleteModel(
            name='UnicomOrders',
        ),
    ]
