# Generated by Django 5.0 on 2024-05-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_delete_unicomorderitems_delete_unicomorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uniCode',
            new_name='uni_code',
        ),
    ]
