# Generated by Django 5.0 on 2024-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_unicode_order_uni_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_priority',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
