# Generated by Django 5.0 on 2024-05-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uni_shipment_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
