# Generated by Django 5.0 on 2024-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_uni_shipment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='erp_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='erp_id',
            field=models.UUIDField(null=True),
        ),
    ]
