# Generated by Django 5.0 on 2024-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_erp_id_orderitem_erp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='erp_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='erp_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
